---
collections:
- name: netbox.netbox
  source: https://galaxy.ansible.com
- name: community.general
  source: https://galaxy.ansible.com
- name: community.crypto
  source: https://galaxy.ansible.com