  - name: generate signing key
    community.crypto.openssl_privatekey:
      path: "/tmp/{{ dns_label }}.{{ dns_zone }}.pem"
      return_content: True
      size: 4096
    delegate_to: localhost
    register: generated_private_key

  - name: generate csr
    community.crypto.openssl_csr:
      path: "/tmp/{{ dns_label }}.{{ dns_zone }}.csr"
      privatekey_content: "{{ generated_private_key.privatekey }}"
      common_name: "{{ dns_label }}.{{ dns_zone }}"
      subject_alt_name: "DNS:{{ dns_label }}.{{ dns_zone }}"
      return_content: True
    delegate_to: localhost
    register: generated_csr