  - name: generate signing key
    openssl_privatekey:
      path: "/tmp/{{ dns_name }}.pem"
      return_content: True
      size: 2048
    delegate_to: localhost
    register: generated_private_key

  - name: generate csr
    openssl_csr:
      path: "/tmp/{{ dns_name }}.csr"
      privatekey_content: "{{ generated_private_key.privateKey }}"
      common_name: "{{ dns_name }}"
      subject_alt_name: "DNS:{{ dns_name | join(',DNS:') }}"
      return_content: True
    delegate_to: localhost