    - name: Create ACME DNS-01 challenge
      acme_certificate:
        acme_version: 2
        terms_agreed: yes
        account_key_content: "{{ acmeAccountKey }}"
        csr_content: "{{ generated_csr.csr }}"
        dest: "/tmp/{{ dns_name }}.crt"
        fullchain_dest: "/tmp/{{ dns_name }}-fullchain.crt"
        challenge: dns-01
        # acme_directory: https://acme-v02.api.letsencrypt.org/directory
        acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        remaining_days: 60
      register: challenge
      delegate_to: localhost