  - name: Create ACME DNS-01 challenge
    acme_certificate:
      acme_version: 2
      terms_agreed: yes
      account_key_content: "{{ acmeAccountKey }}"
      csr_content: "{{ generated_csr.csr }}"
      dest: "/tmp/{{ dns_name }}.crt"
      fullchain_dest: "/tmp/{{ dns_name }}-fullchain.crt"
      challenge: dns-01
      # acme_directory: https://acme-v02.api.letsencrypt.org/directory
      acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
      remaining_days: 60
    register: acme_challenge
    delegate_to: localhost

  - name: Propagate ACME DNS-01 challenge
    community.general.nsupdate:
      key_name: "{{ rfc2136TsigKey.name }}"
      key_algorithm: "{{ rfc2136TsigKey.algorithm }}"
      key_secret: "{{ rfc2136TsigKey.secret }}"
      server: "{{ rfc2136TsigKey.primaryNS }}"
      zone: "{{ dns_name.split('.')[1:] | join('.') }}"
      record: "_acme-challenge.{{ dns_name.split('.')[0] }}"
      type: TXT
      value: "{{ acme_challenge.challenge_data_dns.values() | last | last }}"
    register: nsupdate_result
    delegate_to: localhost

  - name: Debugging nsupdate_result
    debug:
      msg: "{{ nsupdate_result }}"
    delegate_to: localhost
  
  