- hosts: esxi_hosts
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Debugging acmeAccountKey
      debug:
        msg: "{{ acmeAccountKey }}"
      delegate_to: localhost
    - name: Debugging dns_name
      debug:
        msg: "{{ dns_name }}"
      delegate_to: localhost

    - name: generate signing key
      openssl_privatekey:
        path: "/tmp/{{ dns_name }}.pem"
        return_content: True
        size: 2048
      delegate_to: localhost
      register: generated_private_key

    - name: generate csr
      openssl_csr:
        path: "/tmp/{{ dns_name }}.csr"
        privatekey_content: "{{ generated_private_key.privateKey }}"
        common_name: "{{ dns_name }}"
        subject_alt_name: "DNS:{{ dns_name | join(',DNS:') }}"
        return_content: True
      delegate_to: localhost
      register: generated_csr

    - name: Debugging generated_private_key
      debug:
        msg: "{{ generated_private_key }}"
      delegate_to: localhost

    - name: Debugging generated_csr
      debug:
        msg: "{{ generated_csr }}"
      delegate_to: localhost