- hosts: esxi_hosts
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Install dnspython python package
      ansible.builtin.pip:
        name: dnspython
      delegate_to: localhost

    - name: generate signing key
      community.crypto.openssl_privatekey:
        path: "/tmp/{{ dns_name }}.pem"
        return_content: True
        size: 4096
      delegate_to: localhost
      register: generated_private_key
    
    - name: Debugging generated_private_key
      debug:
        msg: "{{ generated_private_key }}"
      delegate_to: localhost

    - name: generate csr
      community.crypto.openssl_csr:
        path: "/tmp/{{ dns_name }}.csr"
        privatekey_content: "{{ generated_private_key.privatekey }}"
        common_name: "{{ dns_name }}"
        subject_alt_name: "DNS:{{ dns_name }}"
        return_content: True
      delegate_to: localhost
      register: generated_csr

    - name: Debugging generated_csr
      debug:
        msg: "{{ generated_csr }}"
      delegate_to: localhost

    - name: Create ACME DNS-01 challenge
      acme_certificate:
        acme_version: 2
        terms_agreed: yes
        account_key_content: "{{ acmeAccountKey }}"
        csr_content: "{{ generated_csr.csr }}"
        dest: "/tmp/{{ dns_name }}.crt"
        fullchain_dest: "/tmp/{{ dns_name }}-fullchain.crt"
        challenge: dns-01
        # acme_directory: https://acme-v02.api.letsencrypt.org/directory
        acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        remaining_days: 60
      register: acme_challenge
      delegate_to: localhost

    - name: Debugging acme_challenge
      debug:
        msg: "{{ acme_challenge }}"
      delegate_to: localhost

    - name: Remove old ACME DNS-01 challenge
      community.general.nsupdate:
        key_name: "{{ rfc2136TsigKey.name }}"
        key_algorithm: "{{ rfc2136TsigKey.algorithm }}"
        key_secret: "{{ rfc2136TsigKey.secret }}"
        server: "{{ rfc2136TsigKey.primaryNS }}"
        zone: "{{ dns_name }}"
        record: "_acme-challenge"
        type: TXT
        state: absent
      delegate_to: localhost

    - name: Propagate ACME DNS-01 challenge
      community.general.nsupdate:
        key_name: "{{ rfc2136TsigKey.name }}"
        key_algorithm: "{{ rfc2136TsigKey.algorithm }}"
        key_secret: "{{ rfc2136TsigKey.secret }}"
        server: "{{ rfc2136TsigKey.primaryNS }}"
        zone: "{{ dns_name }}"
        record: "_acme-challenge"
        type: TXT
        value: "{{ acme_challenge.challenge_data_dns.values() | last | last }}"
      register: nsupdate_result
      delegate_to: localhost
   
    - name: Debugging nsupdate_result
      debug:
        msg: "{{ nsupdate_result }}"
      delegate_to: localhost
  
    - name: Validate ACME DNS-01 challenge
      acme_certificate:
        acme_version: 2 
        account_key_content: "{{ acmeAccountKey }}"
        csr_content: "{{ generated_csr.csr }}"
        dest: "/tmp/{{ dns_name }}.crt"
        fullchain_dest: "/tmp/{{ dns_name }}-fullchain.crt"
        chain_dest: "/tmp/{{ dns_name }}-intermediate.crt"
        challenge: dns-01
        # acme_directory: https://acme-v02.api.letsencrypt.org/directory
        acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        remaining_days: 60
        data: "{{ acme_challenge }}"
      when: acme_challenge is changed
      register: acme_certificate_result
      delegate_to: localhost
  
    - name: Debugging acme_certificate_result
      debug:
        msg: "{{ acme_certificate_result }}"
      delegate_to: localhost
      