- hosts: esxi_hosts
  become_method: sudo
  gather_facts: false
  tasks:
    - name: generate signing key
      community.crypto.openssl_privatekey:
        path: "/tmp/{{ dns_name }}.pem"
        return_content: True
        size: 4096
      delegate_to: localhost
      register: generated_private_key
    
    - name: Debugging generated_private_key
      debug:
        msg: "{{ generated_private_key }}"
      delegate_to: localhost

    - name: generate csr
      community.crypto.openssl_csr:
        path: "/tmp/{{ dns_name }}.csr"
        privatekey_content: "{{ generated_private_key.privatekey }}"
        common_name: "{{ dns_name }}"
        subject_alt_name: "DNS:{{ dns_name | join(',DNS:') }}"
        return_content: True
      delegate_to: localhost
      register: generated_csr

    - name: Debugging generated_csr
      debug:
        msg: "{{ generated_csr }}"
      delegate_to: localhost

    - name: Create ACME DNS-01 challenge
      acme_certificate:
        acme_version: 2
        terms_agreed: yes
        account_key_content: "{{ acmeAccountKey }}"
        csr_content: "{{ generated_csr.csr }}"
        dest: "/tmp/{{ dns_name }}.crt"
        fullchain_dest: "/tmp/{{ dns_name }}-fullchain.crt"
        challenge: dns-01
        # acme_directory: https://acme-v02.api.letsencrypt.org/directory
        acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        remaining_days: 60
      register: acme_challenge
      delegate_to: localhost

    - name: Debugging acme_challenge
      debug:
        msg: "{{ acme_challenge }}"
      delegate_to: localhost

