- hosts: localhost
  become_method: sudo
  gather_facts: true
  tasks:
    - name: Debugging acmeAccountKey
      debug:
        msg: "{{ acmeAccountKey }}"
    - name: Debugging dns_name
      debug:
        msg: "{{ dns_name }}"
